# Generated by Django 5.1 on 2024-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
